# -*- coding: utf-8 -*-
"""04_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jgNS_wH-7bouXXAjQdBJrtOw2fypa3UJ
"""

import torch

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[1,2],[3,4],[5,6]])

z = torch.matmul(x,y)

z

import torch

x1 = torch.FloatTensor([[[1,2,3],[4,5,6]]]) # 2,3
y1 = torch.FloatTensor([[[1,2],[3,4],[5,6]]])  # 3,2

result1 = torch.bmm(x1,y1)
result1_1 = torch.matmul(x1,y1)

x2 = torch.FloatTensor([[[3,4,5],[1,2,3]]])
y2 = torch.FloatTensor([[[5,1],[4,2],[3,3]]])

result2 = torch.bmm(x2,y2)
result2_1 = torch.matmul(x2,y2)


x3 = torch.FloatTensor([[[5,6,7],[4,5,6]]])
y3 = torch.FloatTensor([[[2,3],[2,3],[2,3]]])

result3 = torch.bmm(x3,y3)
result3_1 = torch.matmul(x3,y3)



print("bmm")
print(result1)
print()
print(result2)
print()
print(result3)

print("matmul")
print(result1_1)
print()
print(result2_1)
print()
print(result3_1)

